## Numpy

### Introduction:

* Numpy stands for "Numerical Python"
* It is the fundamental package for numerical calculations.
* Supports N-dimensional array objects that can be used for processing multi-dimensional data.
* Supports different datatypes.

#### Using Numpy we can perform the following :

* Mathematical & logical operation on arrays
* Fourier transformation
* Linear algebra operations
* Random number generations

---

### Creating an Numpy array

An array is an ordered collection of elements of basic datatypes of given length. <br>
The Numpy can handle different categorical entries, as well.

***Syntax :***

```python
numpy.array(object)
```

***Example :***

In [1]:
# Importing the numpy

import numpy as np

x = np.array([2,3,4,5])
print(x)

[2 3 4 5]


In [2]:
# To see the datatype of "x"

print(type(x))

<class 'numpy.ndarray'>


In [3]:
# Handling different categorical entries:

y = np.array(['2','3','n','5'])
print(y)

['2' '3' 'n' '5']


In [4]:
# All elements are coerced to the same data type, i.e, Numpy array

print(type(y))

<class 'numpy.ndarray'>


---

### Generating arrays using `linspace()`


`numpy.linspace()` -: Returns equally spaced numbers within a given range based on the sample number

__*Syntax :*__

```python
numpy.linspace(start, stop, num, dtype, endpoint ,retstep)
```

* `start` - start of interval range
* `stop` - end of interval range
* `num` - number of samples to be generated
* `dtype` - type of output array (By default = float type)
* `endpoint` - "True" to include the "stop" value as endpoint
* `retstep` - returns the sample, step value (By default = True)

__*For Example :*__ We can generate an array "b" with `start = 1` and `stop = 5`, as follows :

In [7]:
b = np.linspace(start = 1, stop = 5, num = 10, endpoint = True ,retstep = False)
print(b)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


Specifying `retstep = True` returns the sample as well as the step value.

In [15]:
c = np.linspace(start=1, stop=5, num=10, endpoint=True, retstep=True)
print(c)

(array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ]), 0.4444444444444444)


## Generating arrays using `arange()`
---

`numpy.arange()` - Returns equally spaced numbers within a given range based on the step size.

***Syntax :***

```python
numpy.arange(start, stop, step)
```
* `start` - start of interval range
* `stop` - stop of interval range
* `step` - step size of the interval range

***For Example :*** We can generate an array with `start = 1` and `stop = 10` by specifying `step = 2`, as follows :

In [8]:
d = np.arange(start = 1, stop = 10, step = 2)
print(d)

[1 3 5 7 9]


## Generating arrays using `ones()`
---

`numpy.ones()` - Returns an array with given shape and type filled with ones.

***Syntax :***

```python
numpy.ones(shape, dtype)
```

* `shape` - integer or, sequence of integers
* `dtype` - datatype (default = float type)

***For Example :*** We can create a $(3 \times 4)$ matrix with each element as `1`, as follows :

In [9]:
one = np.ones((3,4))
print(one)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


## Generating arrays using `zeros()`
---

`numpy.zeros()` - Returns an array with given shape and type filled with zeros.

***Syntax :***

```python
numpy.zeros(shape, dtype)
```

* `shape` - integer or, sequence of integers
* `dtype` - datatype (default = float type)

***For Example :*** We can create a $(3 \times 4)$ matrix with each element as `0`, as follows :

In [10]:
zero = np.zeros((3,4))
print(zero)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


## Generating arrays using `random.rand()`
---
`numpy.random.rand` - Returns an array of given shape filled with random values.

***Syntax :***

```python
numpy.random.rand(shape)
```

* `shape` - integer or, sequence of intergers

***For Example :*** We can create a one-dimesional array with random numbers, as follows :

In [11]:
random = np.random.rand(5)
print(random)

[0.61124198 0.79778626 0.71576555 0.29445028 0.65206894]


We can also generate a $(5 \times 2)$ matrix with random elements, as follows :

In [12]:
random_mat = np.random.rand(5,2)
print(random_mat)

[[0.05063866 0.00480178]
 [0.33513803 0.46176556]
 [0.80555573 0.73949105]
 [0.74259559 0.76112722]
 [0.01783647 0.53699179]]


## Generating arrays using `logspace()`
---

`numpy.logspace` - Returns equally spaced numbers based on log scale.

***Syntax :***

```python
numpy.logspace(start, stop, num, endpoint, base, dtype)
```

* `start` - Start value of the sequence
* `stop` - Stop value of the sequence
* `num` - Number of samples to be generated (Default : 50)
* `endpoint` - If `True` then, `stop` is the last sample
* `base` - Base of the logspace (Default : 10.0)
* `dtype` - Type of the output array

***For Example :*** We can get a 5 sample array with logarithimic base = 10, as follows :

In [13]:
logs = np.logspace(start = 1, stop = 10, num = 5, base = 10.0, endpoint = True)
print(logs)

[1.00000000e+01 1.77827941e+03 3.16227766e+05 5.62341325e+07
 1.00000000e+10]


## Advantages of Numpy
---

* Numpy supports vectorized operations
* Array operations are caried out in "C" and hence the universal functions in numpy are faster than operations carried out on python lists.

### Advantages of Numpy - Speed
---

* `%timeit` module can be used to measure the execution time for snippets of code.
* Let's compare the processing speed of the list and an array using an addition operation.

In [15]:
#Creating a list

lst = range(1000)
%timeit sum(lst)

35.5 µs ± 1.8 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [16]:
#Creating a numpy array

numarr = np.array(lst)
%timeit np.sum(numarr)

10.9 µs ± 450 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


We can clearly see that the numpy array works faster than the python list

### Advantages of Numpy - Storage Space
---

* `getsizeof()` - Retuns the size of the object in bytes.

***Syntax :***

```python
sys.getsizeof(object)
```
* `itemsize` - Returns the size of one element of numpy array

***Syntax :***

```python
numpy.ndarray.itemsize
```

Size of the list/array can be found by multiplying the size of an individual element with the number of elements in the list/array.


Let's compare the list "lst" and the array "numarr" to find the memory used by each at runtime :

In [17]:
import sys
sys.getsizeof(1)*len(lst)

28000

In [18]:
numarr.itemsize * numarr.size

4000

We can clearly see that the numpy array uses less bytes for storage than the python list.

## Reshaping an array
---

`reshape()` - Recasts an array in a new shape without changing its data.

In [33]:
grid = np.arange(start = 1, stop = 10).reshape(3,3)
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Array Dimensions
---

`shape` - Returns the dimension of an array

***Syntax :***

```python
array_name.shape
```

In [35]:
#Create an array "a"

a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
a.shape

[[1 2 3]
 [4 5 6]
 [7 8 9]]


(3, 3)

## Numpy Addition
---

* `numpy.sum()` - Returns the sum of all array elements or, sum of all array elements over a given axis

***Syntax :***

```python
numpy.sum(array, axis)
```
In the above syntax -:

* `array()` - Input array
* `axis` - axis along which the sum should be calculated

In [37]:
print(np.sum(a)) #Calculates the sum of all the elements in the arrays

print(np.sum(a, axis = 0)) #Calculates the sum of elements along the column (axis = 0)

print(np.sum(a, axis = 1)) #Calculates the sum of elements along the row (axis = 1)

45
[12 15 18]
[ 6 15 24]


`numpy.add()` - Performs the elementwise addition between two arrays

***Syntax :***

```python
numpy.add(array_1, array_2)
```

In [19]:
#Let's create 2 arrays

m = np.arange(start = 1, stop = 10).reshape(3,3)
n = np.arange(start = 11, stop = 20).reshape(3,3)

print(m)
print(n)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [20]:
#Let's perform the elementwise addition

add_result = np.add(m,n)
print(add_result)

[[12 14 16]
 [18 20 22]
 [24 26 28]]


* `numpy.multiply()` - Performs elementwise multiplication between two arrays
* `numpy.subtract()` - Perfroms elementwise subtraction between two arrays
* `numpy.divide()` - Performs elementwise division between two arrays
* `numpy.remainder()` - Retruns elementwise remainder of division between two arrays

In [21]:
#Let's perform elementwise subtraction

subtract_result = np.subtract(n,m)
print(subtract_result)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [22]:
#Let's perform elementwise multiplication

mult_result = np.multiply(m,n)
print(mult_result)

[[ 11  24  39]
 [ 56  75  96]
 [119 144 171]]


In [23]:
#Let's perform matrix multiplication

mult = np.dot(m,n)
print(mult)

[[ 90  96 102]
 [216 231 246]
 [342 366 390]]


In [24]:
#Let's perform elementwise division

div_result = np.divide(n,m)
print(div_result)

[[11.          6.          4.33333333]
 [ 3.5         3.          2.66666667]
 [ 2.42857143  2.25        2.11111111]]


In [25]:
#Let's extract the remainder from the division

rem_result = np.remainder(n,m)
print(rem_result)

[[0 0 1]
 [2 0 4]
 [3 2 1]]


## Accessing components of an array
---

Components of an array can be accessed using the index number.

***For Example :*** Let's create a $(3 \times 3)$ matrix to perform slicing operations :

In [28]:
A = np.array([[25,35,65],[23,43,16],[10,23,46]])
print(A)

[[25 35 65]
 [23 43 16]
 [10 23 46]]


In [29]:
# To extract element at 1st row and 2nd column position :

print(A[0,1])

35


In [30]:
# Extract all the elements of the array excluding 1st row :

print(A[1:3])

[[23 43 16]
 [10 23 46]]


In [32]:
# Extract elements from first column only :

print(A[:,0])

[25 23 10]


In [33]:
# extract a sub-matrix with first 2 rows and first 2 columns :

print(A[:2,:2])

[[25 35]
 [23 43]]


## Modifying components of an array
---

We can also modify the componet of an numpy array using indexing :

***For Example :*** We can change the first element of matrix `A` to $0$, as follows :

In [35]:
A[0,0] = 0
print(A)

[[ 0 35 65]
 [23 43 16]
 [10 23 46]]


If we create a subset using the original matrix `A` and change its element then, it also updates the original array.

### Modifying array using `transpose()`

`numpy.transpose()` - Permute the dimension of array.

***Syntax :***
```python
np.transpose(array)
```
***For Example :*** We can transpose the array `A`, as follows :

In [36]:
At = np.transpose(A)
print(At)

[[ 0 23 10]
 [35 43 23]
 [65 16 46]]


### Modifying array using `append()`

`append()` - Adds values at the end of the array.

***Syntax :***
```python
np.append(array, axis)
```
***For Example :*** We can add an new array `a` to the original the array `A` as a row, as follows :

In [38]:
a = [[2,3,4]]

A_app = np.append(A,a, axis=0)
print(A_app)

[[ 0 35 65]
 [23 43 16]
 [10 23 46]
 [ 2  3  4]]


To add a new array `p` as a column to the original array `A`, we first have to reshape it and then, we need to append it, as follows :

In [39]:
p = np.array([1,2,3]).reshape(3,1)

A_appc = np.append(A,p, axis=1)
print(A_appc)

[[ 0 35 65  1]
 [23 43 16  2]
 [10 23 46  3]]


### Modifying array using `insert()`

`insert()` - Adds values at a given position and axis in an array.

***Syntax :***
```python
np.insert(array, obj, values, axis)
```
- `array` : Input array
- `obj` : Index position
- `values` : Array of values to be inserted
- `axis` : Axis along which values should be inserted

***For Example :*** We can add an new array `q` to the original the array `A` as a row, as follows :